services:
    ekapustadoctrinecustomtypes.schemacolumn.listener:
        public: false
        class: Ekapusta\DoctrineCustomTypesBundle\EventListener\DoctrineSchemaColumnDefinitionListener
        tags:
            - {name: doctrine.event_listener, event: onSchemaColumnDefinition}
